/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF, useMatcapTexture, useTexture } from '@react-three/drei';
import * as THREE from 'three';
import { useFrame } from '@react-three/fiber';

export default function Model(props) {
    const { nodes } = useGLTF('./LowPolyEarth2.glb');

    useMatcapTexture;
    const matcapSnowTexture = useTexture('./matcap/stone.png');
    const matcapTreeTexture = useTexture('./matcap/leaves.png');
    const matcapLandTexture = useTexture('./matcap/ground.png');
    const matcapDesertTexture = useTexture('./matcap/wood.png');
    const matcapTrunkTexture = useTexture('./matcap/trunk.png');

    const cloudMaterial = new THREE.MeshMatcapMaterial({
        color: new THREE.Color('#ffffff').convertSRGBToLinear(),
        transparent: true,
        opacity: 0.6,
    });

    const oceanMaterial = new THREE.MeshMatcapMaterial({
        color: new THREE.Color('#D6EFFF').convertSRGBToLinear(),
        transparent: true,
        opacity: 0.9,
    });

    const snowMaterial = new THREE.MeshMatcapMaterial({
        color: new THREE.Color('#ffffff').convertSRGBToLinear(),
        transparent: false,
        opacity: 1,
        matcap: matcapSnowTexture,
    });

    const groundMaterial = new THREE.MeshMatcapMaterial({
        color: new THREE.Color('#ffffff').convertSRGBToLinear(),
        transparent: false,
        opacity: 1,
        matcap: matcapLandTexture,
    });

    const leavesMaterial = new THREE.MeshMatcapMaterial({
        color: new THREE.Color('#ffffff').convertSRGBToLinear(),
        transparent: false,
        opacity: 1,
        matcap: matcapTreeTexture,
    });

    const desertMaterial = new THREE.MeshMatcapMaterial({
        color: new THREE.Color('#ffffff').convertSRGBToLinear(),
        transparent: false,
        opacity: 1,
        matcap: matcapDesertTexture,
    });

    const trunkMaterial = new THREE.MeshMatcapMaterial({
        color: new THREE.Color('#ffffff').convertSRGBToLinear(),
        transparent: false,
        opacity: 1,
        matcap: matcapTrunkTexture,
    });

    const cloudRef = useRef();
    const globeRef = useRef();
    useFrame(({ clock }) => {
        cloudRef.current.rotation.x = -clock.getElapsedTime() / 15;
        cloudRef.current.rotation.y = -clock.getElapsedTime() / 13;
        cloudRef.current.rotation.z = clock.getElapsedTime() / 12;
        globeRef.current.rotation.y = clock.getElapsedTime() / 15;
    });

    return (
        <group ref={globeRef} {...props} dispose={null}>
            <group scale={1.03}>
                <mesh
                    receiveShadow
                    geometry={nodes.Icosphere.geometry}
                    material={oceanMaterial}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Icosphere_1.geometry}
                    material={snowMaterial}
                />
            </group>
            <mesh
                ref={cloudRef}
                castShadow
                geometry={nodes.Clouds.geometry}
                material={cloudMaterial}
                scale={1.4}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere.geometry}
                material={groundMaterial}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere_1.geometry}
                material={snowMaterial}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere_2.geometry}
                material={desertMaterial}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere_3.geometry}
                material={leavesMaterial}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere_4.geometry}
                material={trunkMaterial}
            />
        </group>
    );
}

useGLTF.preload('/LowPolyEarth2.glb');
